spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user_admin
    password: user_password
  liquibase:
    change-log: db/liquibase/changelog.xml
    url: jdbc:postgresql://localhost:5432/user_db
    user: user_admin
    password: user_password

streaming:
  enabled: true
  outbox:
    table-name: outbox_messages

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      percentiles:
        "[http.server.requests]": 0.5, 0.75, 0.95, 0.99
    tags:
      application: ${spring.application.name}
      environment: local